# docker-compose.yml

# Specify the version of Docker Compose to use
version: '3.8'

# Define the services that make up the application
services:
  # The app service uses a build context relative to the location of the docker-compose.yml file
  # and a specific Dockerfile if there are multiple Dockerfiles in the build context
  app:
    build: ./app
    dockerfile: Dockerfile
    # Restart the container if it exits
    restart: always
    # Map the host's port 5000 to the container's port 500
